### ISSUE TITLE
About  the output range imge

### ISSUE THREAD

**Issue by derowtosky** [hancyran/LiDAR-Diffusion#6]
thanks for your excellent work! i'm little confused while i'm reading your paper：the output depth map is absolute depth or relative depth, that is, the depth in the output depth map is the true value or the relative value？

**Comment by hancyran** [comment]
It is an absolute depth, which can be directly converted into 3D point cloud without distortion given some predefined parameters (like fov). Here is a [function ](https://github.com/hancyran/LiDAR-Diffusion/blob/3f16bf03d48e5f1fa1ad59d73a01a3287af28f72/lidm/utils/lidar_utils.py#L97C5-L97C14) for your reference.

**Comment by derowtosky** [comment]
so, in the 'Camera-to-LiDAR' part, the model can just use the RGB image to generate the real depth image? that's awesome!

**Comment by hancyran** [comment]
@derowtosky Exactly! Here we adopt CLIP global feature of an image as the condition for our LiDAR Diffusion to generate the corresponding LiDAR point cloud. However, note that due to the KITTI-360 dataset's limitation, in which the camera did not cover the whole LiDAR scene, the generated LiDAR may be unconditional within the uncovered area. In our paper, we just implement this simple pipeline. 

For a real and more appropriate Camera-to-LiDAR, I suggest to train LiDAR Diffusion on nuScenes, which provides six cameras covering the whole scene (360 degrees) as the condition for LiDAR point cloud generation. Also, extracting camera patch features and incorporating camera parameters would lead to a more promising generator.

**Comment by derowtosky** [comment]
@hancyran thanks for your reply
