### ISSUE TITLE
Convert into onnx format 

### ISSUE THREAD

**Issue by BasemAbusaif** [hancyran/LiDAR-Diffusion#9]
can you share a document how to convert the diffusion model into onnx format?

**Comment by hancyran** [comment]
Sorry, I am not familiar with onnx format. I may not be able to provide its doc right now, but I am pretty sure that you can consider LiDAR Diffusion a variant of Stable Diffusion/Latent Diffusion. In this way, the problem seems much easier. 

Here is a relevant repo [Stable-Diffusion-ONNX-FP16](https://github.com/Amblyopius/Stable-Diffusion-ONNX-FP16) I think will be helpful in your case. Remember that the VAE part will be a bit different from Stable Diffusion, so you can follow the instruction in the [Use Alternative VAE](https://github.com/Amblyopius/Stable-Diffusion-ONNX-FP16?tab=readme-ov-file#use-alternative-vae).

**Comment by hancyran** [comment]
Closed due to inactivity

**Comment by BasemAbusaif** [comment]
Sorry for late response, I follow the instruction the Stable-Diffusion-ONNX-FP16 repo and I found that I need json file called model_index.json that have all the information about diffusion model and other one for VAE can you provide example of your model?
